# Generated by Django 4.1.3 on 2023-11-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_member1_name', models.CharField(max_length=100)),
                ('tem_member2_name', models.CharField(max_length=100)),
                ('team_member1_email', models.EmailField(max_length=100)),
                ('team_member2_email', models.EmailField(max_length=100)),
                ('Leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.leadermodle')),
            ],
        ),
    ]
