# Generated by Django 4.1.3 on 2023-11-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_teammodle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammodle',
            old_name='tem_member2_name',
            new_name='team_member2_name',
        ),
    ]
