# Generated by Django 4.1.3 on 2023-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_rename_tem_member2_name_teammodle_team_member2_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadermodle',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
