# Generated by Django 4.1.3 on 2023-11-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_leadermodle_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodle',
            name='team_member1_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teammodle',
            name='team_member2_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
